# -*- coding: utf-8 -*-
"""Lab2-AI-JesusM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NP2dFZikPvxiYdt5tGQjqS39j0cCCHRZ
"""

import pandas as pd
import numpy as np
import seaborn as sns
sns.set_theme (style = "whitegrid")
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

from google.colab import drive
drive.mount('/content/drive')

dfbankloan = pd.read_excel('/content/drive/MyDrive/Lab-AI/Bankloan descargable.xls', sheet_name=0)
dfTrainingData = pd.read_excel('/content/drive/MyDrive/Lab-AI/Bankloan descargable.xls', sheet_name=1)

print("Dimensiones de los datos para entrenamiento: ", dfbankloan.shape)
print("Dimensiones de los datos para entrenamiento: ", dfTrainingData.shape)

dfbankloan.info()

dfTrainingData.info()

dfbankloan[dfbankloan['Age'] > 100]

dfbankloan = dfbankloan[dfbankloan['Age'] <= 100].copy()

dfbankloan.head()

print(dfbankloan['Nationality'].value_counts())

dfTrainingData.head()

dfbankloan.describe()

"""La edad max es 1970, lo cual no es coherente con el resto de valores y la media.

Hay un valor de la columna income que tiene un valor de -149 lo cual no tiene sentido.

El promedio y la desviacion estandar de la columna 'customer' no tiene sentido.
"""

dfbankloan[dfbankloan['Income'] < 0]

dfbankloan = dfbankloan[dfbankloan['Income'] >= 0]

# La fila con Income negative ya no esta

dfbankloan.describe()

# Calculando IQR

Q1 = dfbankloan['Income'].quantile(0.25)
Q3 = dfbankloan['Income'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR # Corrected: Standard upper bound for outliers is Q3 + 1.5 * IQR

print(f"Original DataFrame shape: {dfbankloan.shape[0]}") # Use shape[0] for row count

# Elimando outliers
# Keep rows where 'Income' is within the calculated bounds
dfbankloan = dfbankloan[((dfbankloan['Income'] >= lower_bound) & (dfbankloan['Income'] <= upper_bound))]

print(f"DataFrame shape after outlier removal: {dfbankloan.shape[0]}") # Use shape[0] for row count

dfTrainingData.describe()

bank_missing_values = dfbankloan.isnull().sum()
print(bank_missing_values)

# Imputar los datos de la columna Age con la media de los datos

dfTrainingData['Age'] = dfTrainingData['Age'].fillna(dfTrainingData['Age'].median())
training_missing_values = dfTrainingData.isnull().sum()
print("Missing values en la columna Age: ", training_missing_values['Age'])

# Imputar los datos de la columna Income con la media de los datos

dfTrainingData['Income'] = dfTrainingData['Income'].fillna(dfTrainingData['Income'].median())
print("Missing values en la columna Income: ", training_missing_values['Income'])

#no_na_dfbankloan = dfbankloan.loc[dfbankloan['Income'] < 0, ['Income']] = np.nan
#print(no_na_dfbankloan)
#
#no_na_dfTrainingData = dfTrainingData.loc[dfTrainingData['Income'] < 0, ['Income']] = np.nan

dfbankloan['Default'].map({'S': 'Si', 'N': 'No'}).value_counts()

# Visualizar cuantos clientes han incumplido su prestamo

plt.figure(figsize=(6, 4))
sns.countplot(data=dfbankloan, x='Default', palette='Set2')
plt.title('Distribucion de Clientes: Cumplidos vs Incumplidos')
plt.show()

# Ver el porcentaje exacto
print(dfbankloan['Default'].value_counts(normalize=True) * 100)

# Como se distribuyen los ingresos (Income) o la edad (Age) de los clientes?
from matplotlib import axes

fig, axes = plt.subplots(1, 2, figsize=(12, 6))
sns.histplot(dfbankloan['Age'], kde=True, ax=axes[0], color='skyblue')
axes[0].set_title('Distribucion de la Edad de los Clientes')

sns.histplot(dfbankloan['Income'], kde=True, ax=axes[1], color='salmon')
axes[1].set_title('Distribucion de los Ingresos')

plt.tight_layout()
plt.show()

default = dfbankloan[dfbankloan['Default'] == 'S']
no_default = dfbankloan[dfbankloan['Default'] == 'N']

default = default.drop(['Default', 'Nationality', 'Education'], axis=1)
no_default = no_default.drop(['Default', 'Nationality', 'Education'], axis=1)

print(f"\nPrinting first 5 rows of clients who defaulted: \n{default.head()}" )
print(f"\nPrinting first 5 rows of clients who didnt default: \n {no_default.head()}")
print()
display(default.corr())

plt.hist(default['Age'], bins=20)
plt.title('Distribucion de la Edad de los Clientes Incumplidos')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()

plt.hist(no_default['Age'], bins=20)
plt.title('Distribucion de la Edad de los Clientes Cumplidos')
plt.xlabel('Edad')
plt.ylabel('Frecuencia')
plt.show()

sns.set_style("whitegrid")
sns.color_palette("flare", as_cmap=True)
plt.figure(figsize=(12, 6))

plt.title('Correlacion de las Variables Numericas de los Clientes Incumplidos')
sns.heatmap(default.corr(), annot=True)
plt.show()

plt.hist(default['Income'], bins=20)
plt.title('Distribucion de los Ingresos de los Clientes Incumplidos')
plt.xlabel('Ingresos')
plt.ylabel('Frecuencia')
plt.show()

plt.hist(no_default['Income'], bins=20)
plt.title('Distribucion de los Ingresos de los Clientes Cumplidos')
plt.xlabel('Ingresos')
plt.ylabel('Frecuencia')
plt.show()

sns.set_style("whitegrid")
sns.color_palette("flare", as_cmap=True)
plt.figure(figsize=(12, 6))

plt.title('Correlacion de las Variables Numericas de los Clientes Cumplidos')
sns.heatmap(no_default.corr(), annot=True)
plt.show()

# Los clientes con menores ingresos tienen a incumplir mas?

plt.figure(figsize=(8, 6))
sns.boxplot(data=dfbankloan, x='Default', y='Income', palette='Set1')
plt.title('Ingresos vs Estado de Incumplimiento (Default)')
#plt.yscale('log') # Escala logaritmica debido a valores extremos
plt.show()

# Para ver como se relacionan las variables numericas entre si (por ejemplo, Deuda vs Edad), calculamos la correlacion de Pearson.

plt.figure(figsize=(10, 8))

# Selecionamos solo las columnas numericas para la corelaccion
numeric_cols = dfbankloan.select_dtypes(include=[np.number])
correlation_matrix = numeric_cols.corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Matrix Correlacion entre Variables Numericas')
plt.show()

"""**1. Observa el mapa de calor (heatmap). Cuales variables tienen correlacion positiva mas fuerte?** - Las variables que mas estan correlacionadas positivamente entre si son (Age)<>(Address) y (Debtinc)<>(OthDebt)

**2. Tienen sentido logico que esas dos caracteristicas esten altamente conectadas?** - Tiene sentido que la variable (Age) y (Address) esten correlacionadas positivamente, ya que es posible que un grupo demografico (rango de edad) vivan en la misma zona?

# Preguntas

1. **Que perfil demografico es mas propenso a incumplir (Default = S)?** - Los jovenes. Rango de edad entre 20-30 anos
2. **Hubo valores atipicos (outliers) que requieran tratamiento antes de entrenar una red neuronal o un arbol de decision?** - Si, en la columna de "Income" y "Age"
3. **Que variables parecen ser las mas importantes para predecir el riesgo?** - La edad.
"""